### ISSUE TITLE
Running the plugin on a spigot server required copying the com/google/protobuf directory to the spigot jar

### ISSUE THREAD

**Issue by Normangorman** [katharosada/botchallenge#10]
Doing this was the only way I could get the plugin to run on my local spigot server (on Arch Linux). This is potentially a problem with spigot/craftbukkit. It could also be a problem with the build process for the plugin, or just a platform specific error. Needs lots of testing on different platforms. A shell script to automate the entire build process would also be nice - as it is currently far from straightforward.

**Comment by katharosada** [comment]
I just checked in https://github.com/katharosada/botchallenge/commit/12d01f100833947741338d348d8f586f76c8bb83 which fixes this issue.

See the description of the problem in the referenced bug.  :)
