### ISSUE TITLE
Support for robot chat?

### ISSUE THREAD

**Issue by Normangorman** [katharosada/botchallenge#7]
It would be a nice feature to allow robots to talk on server chat - e.g. robot.chat("Hello!"). How difficult would this be to implement? I'd love to contribute but I don't have the Java experience :(

**Comment by katharosada** [comment]
Just an FYI, I rebuilt the plugin with your change and it's live on the europe.botchallenge.net and au.botchallenge.net servers. Thanks so much for this, it works great!
